<#compress>
<#include "helper.ftlinc"/>
<#assign sizeMap = {
       '32':   '32B' ,
       '64':   '64B' ,
      '128':  '128B' ,
      '256':  '256B' ,
      '512':  '512B' ,
     '1024':    '1KB',
     '2048':    '2KB',
     '4096':    '4KB',
     '8192':    '8KB',
    '16384':   '16KB',
    '32768':   '32KB',
    '65536':   '64KB',
   '131072':  '128KB',
   '262144':  '256KB',
   '524288':  '512KB',
  '1048576':    '1MB',
  '2097152':    '2MB',
  '4194304':    '4MB',
  '8388608':    '8MB',
  '16777216':   '16MB',
  '33554432':   '32MB',
  '67108864':   '64MB',
 '134217728': '128MB',
 '268435456': '256MB',
 '536870912': '512MB',
'1073741824':   '1GB',
'2147483648':   '2GB',
'4294967296':   '4GB'
}>
</#compress>
/*
 * MPU Table Source File generated by CMSIS-Zone 
 */
 
#include "mputable.h"

const ARM_MPU_Region_t mpuTable[${zone?filter(x -> x.privilege.u == "1")?size}u][8u] = {
{<#rt>
 <#list zone?filter(x -> x.privilege.u == "1") as z><#rt>
  <#lt> /* Execution Zone '${z.name}' */ 
    <#list z.mpu_setup.region as r>
  // ${r.info} (${r.start}..${r.end})
  { .RBAR = ARM_MPU_RBAR(${r?index}u, ${r.addr_v7M}), <#rt>
    <#lt>.RASR = ARM_MPU_RASR_EX(<#rt>
    	<#lt>${(r.access.x == '1')?then('0', '1')}u, <#rt> 
    	<#lt>ARM_MPU_AP_FULL, <#rt>
    	<#lt>ARM_MPU_ACCESS_${(r.access.p == '1')?then('DEVICE('+r.shared+'u)', 'NORMAL(ARM_MPU_CACHEP_NOCACHE, ARM_MPU_CACHEP_NOCACHE, '+r.shared+'u)')}, <#rt> 
    	<#lt>${r.srd_v7M}u, <#rt>
    	<#lt>ARM_MPU_REGION_SIZE_${sizeMap[hex2num(r.size_v7M)?c]}<#rt>
	<#lt>) }<#rt>
    <#lt><#sep>,
    </#list><#rt>
    <#list z.mpu_setup.region?size..!8><#lt>,
      <#items as r>
  { .RBAR = ARM_MPU_RBAR(${r}u, 0u), .RASR = 0u }<#sep>,
      </#items>
    </#list>

  <#sep>
  <#lt>},{<#rt>
</#list>
}};
