/*
 * MPU Table Header File generated by CMSIS-Zone 
 */

#ifndef MPUTABLE_H

#include "RTE_Components.h"
#include CMSIS_device_header

#define MPUTABLE_NET                  0u
#define MPUTABLE_MAIN                 1u
#define MPUTABLE_BLINKY               2u
#define MPUTABLE_TIMER                3u
#define MPUTABLE_IDLE                 4u

extern const ARM_MPU_Region_t mpuTable[5u][8u];

#endif
